stages:
  - deploy

deploy_maga_production:
  stage: deploy
  tags:
    - maga-prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  resource_group: maga-production
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - bash ci/deploy_prod.sh
